# Configuration for the Flight echo server.
server:
  host: "0.0.0.0"
  port: 8815
  log_file: "server/logs/flight_server.log"
  log_level: "INFO"
  # When true, per-request headers can override delay behaviour.
  allow_header_overrides: true

  delay:
    # Supported strategies: fixed, linear, multiplier, exponential
    strategy: linear
    initial_ms: 250
    linear_increment_ms: 125
    multiplier: 2.0
    exponential_base: 2.0
    max_ms: 5000

  grpc_options:
    - key: "grpc.keepalive_time_ms"
      value: "60000"
    - key: "grpc.keepalive_timeout_ms"
      value: "20000"
    - key: "grpc.http2.max_pings_without_data"
      value: "0"
  tcp_settings:
    tcp_keepalive: true
    tcp_keepidle: 60
    tcp_keepintvl: 10
    tcp_keepcnt: 5
